import type { Notification } from '../types'

export const seedNotifications: Notification[] = [
  {
    id: 'ntf-001',
    at: '2026-05-04T08:15:00',
    kind: 'success',
    title: 'Pointage du jour clôturé',
    body: '94 % de présence sur les chantiers actifs.',
    read: false,
    link: '/ressources/personnel',
  },
  {
    id: 'ntf-002',
    at: '2026-05-04T07:42:00',
    kind: 'warning',
    title: 'Engin ENG-CHG-980H-03 en panne',
    body: 'Devis pompe Rexroth en attente de validation.',
    read: false,
    link: '/validation',
  },
  {
    id: 'ntf-003',
    at: '2026-05-04T07:19:00',
    kind: 'alert',
    title: 'Demande critique — transfert Lauzoua',
    body: 'PRJ-021 → site temporaire. Action attendue avant 12 h.',
    read: false,
    link: '/validation',
  },
  {
    id: 'ntf-004',
    at: '2026-05-04T06:55:00',
    kind: 'info',
    title: 'Rapport quotidien envoyé à la DG',
    body: 'Synthèse opérations et alertes.',
    read: true,
    link: '/reporting',
  },
  {
    id: 'ntf-005',
    at: '2026-05-03T18:42:00',
    kind: 'warning',
    title: 'Consommation anormale 2 engins',
    body: 'Chargeuse 980H et camion benne 740B — à investiguer.',
    read: true,
    link: '/ressources/engins',
  },
  {
    id: 'ntf-006',
    at: '2026-05-03T17:00:00',
    kind: 'info',
    title: 'Rallonge budgétaire en revue',
    body: 'PRJ-021 — 92 M FCFA en attente DG.',
    read: true,
    link: '/validation',
  },
  {
    id: 'ntf-007',
    at: '2026-05-03T14:18:00',
    kind: 'success',
    title: 'Topographie Yaouré validée',
    body: 'Données GPS-RTK intégrées au projet PRJ-041.',
    read: true,
  },
]
