import type { Staff } from '../types'

export const seedStaff: Staff[] = [
  {
    id: 'stf-001',
    matricule: 'RH-001',
    firstName: 'Kouadio',
    lastName: 'Sékongo',
    role: 'Conducteur D9R',
    department: 'Engins lourds',
    presence: 'present',
    projectId: 'prj-001',
    enginId: 'eng-001',
    hireDate: '2018-04-12',
    phone: '+225 07 11 22 33',
    certifications: ['CACES 8', 'Habilitation H0B0', 'Premiers secours'],
  },
  {
    id: 'stf-002',
    matricule: 'RH-002',
    firstName: 'Ahoua',
    lastName: 'Méité',
    role: 'Opératrice pelle',
    department: 'Engins lourds',
    presence: 'absent_justifie',
    projectId: null,
    enginId: 'eng-003',
    hireDate: '2020-09-03',
    phone: '+225 07 44 55 66',
    certifications: ['CACES 4', 'Manipulation explosifs'],
  },
  {
    id: 'stf-003',
    matricule: 'RH-003',
    firstName: 'Bamba',
    lastName: 'Issouf',
    role: 'Superviseur chantier',
    department: 'Supervision',
    presence: 'present',
    projectId: 'prj-002',
    enginId: null,
    hireDate: '2015-02-18',
    phone: '+225 05 12 34 56',
    certifications: ['SST', 'Sauveteur secouriste', 'Audit interne'],
  },
  {
    id: 'stf-004',
    matricule: 'RH-004',
    firstName: 'N’Guessan',
    lastName: 'Gérard',
    role: 'Foreur principal',
    department: 'Forage',
    presence: 'present',
    projectId: 'prj-004',
    enginId: 'eng-006',
    hireDate: '2017-11-20',
    phone: '+225 01 22 88 77',
    certifications: ['BTS Forage', 'Habilitation tirs'],
  },
  {
    id: 'stf-005',
    matricule: 'RH-005',
    firstName: 'Coulibaly',
    lastName: 'Mariam',
    role: 'Conductrice camion',
    department: 'Transport',
    presence: 'mission',
    projectId: 'prj-001',
    enginId: 'eng-004',
    hireDate: '2021-06-01',
    phone: '+225 07 55 11 99',
    certifications: ['Permis Super-Lourd', 'Eco-conduite'],
  },
  {
    id: 'stf-006',
    matricule: 'RH-006',
    firstName: 'Toure',
    lastName: 'Lacina',
    role: 'Mécanicien chef',
    department: 'Maintenance',
    presence: 'present',
    projectId: null,
    enginId: null,
    hireDate: '2014-03-15',
    phone: '+225 05 88 22 11',
    certifications: ['Hydraulique avancée', 'Diagnostic CAT'],
  },
  {
    id: 'stf-007',
    matricule: 'RH-007',
    firstName: 'Ouattara',
    lastName: 'Fatou',
    role: 'Coordinatrice HSE',
    department: 'HSE',
    presence: 'present',
    projectId: 'prj-002',
    enginId: null,
    hireDate: '2019-01-09',
    phone: '+225 07 33 44 22',
    certifications: ['Lead Auditor ISO 45001', 'IOSH'],
  },
  {
    id: 'stf-008',
    matricule: 'RH-008',
    firstName: 'Diabaté',
    lastName: 'Yacouba',
    role: 'Conducteur niveleuse',
    department: 'Engins lourds',
    presence: 'conge',
    projectId: null,
    enginId: 'eng-008',
    hireDate: '2016-10-04',
    phone: '+225 01 44 77 88',
    certifications: ['CACES 6', 'Mécanique de niveau 2'],
  },
  {
    id: 'stf-009',
    matricule: 'RH-009',
    firstName: 'Soro',
    lastName: 'Bintou',
    role: 'Géomètre',
    department: 'Études',
    presence: 'present',
    projectId: 'prj-005',
    enginId: null,
    hireDate: '2022-02-28',
    phone: '+225 05 22 33 44',
    certifications: ['Topographie GPS-RTK', 'AutoCAD Civil'],
  },
  {
    id: 'stf-010',
    matricule: 'RH-010',
    firstName: 'Kassi',
    lastName: 'Eric',
    role: 'Chef d’équipe forage',
    department: 'Forage',
    presence: 'mission',
    projectId: 'prj-004',
    enginId: null,
    hireDate: '2013-08-19',
    phone: '+225 07 66 77 99',
    certifications: ['Tirs miniers', 'Lecture plans géologiques'],
  },
  {
    id: 'stf-011',
    matricule: 'RH-011',
    firstName: 'Brou',
    lastName: 'Edith',
    role: 'Logisticienne',
    department: 'Logistique',
    presence: 'present',
    projectId: 'prj-003',
    enginId: null,
    hireDate: '2020-12-01',
    phone: '+225 01 12 12 21',
    certifications: ['SAP MM', 'Achats publics'],
  },
  {
    id: 'stf-012',
    matricule: 'RH-012',
    firstName: 'Yao',
    lastName: 'Daniel',
    role: 'Opérateur chargeuse',
    department: 'Engins lourds',
    presence: 'maladie',
    projectId: null,
    enginId: 'eng-005',
    hireDate: '2019-07-22',
    phone: '+225 07 88 11 33',
    certifications: ['CACES 4', 'Premiers secours'],
  },
]
